name: 'Check Package Version'
description: 'Check npm package version and whether it has been published yet'
author: 'PostHog'
inputs:
    path:
        required: false
        description: 'Path to the npm package'
        default: '.'
outputs:
    committed-version:
        description: 'Version now commited to the repo'
    published-version:
        description: 'Latest version published to npm, based on `dist-tags`'
    is-new-version:
        description: 'Whether repo version is yet new to npm (`"true"` or `"false"` or `"unknown"`)'
    is-published:
        description: 'Whether repo version has been publish or not to your registry'
runs:
    using: 'node12'
    main: 'dist/index.js'
branding:
    icon: 'loader'
    color: 'orange'
