name: 'Check Package Version'
description: 'A GitHub Action to check and retrieve version information of a Node.js package, including committed and published versions.'
author: 'dupasj'
inputs:
    path:
        required: false
        description: 'The path to the directory containing the package.json file. Default is the root directory.'
        default: '.'
    registry:
        required: false
        description: 'The npm registry URL. If provided, it sets the registry for the duration of the action.'
    scope:
        required: false
        description: ''
    token:
        required: false
        description: 'The authentication token for the npm registry. If provided, it sets the authentication token for the registry.'
    version:
        required: false
        description: 'The version to check. If provided, it overrides the version retrieved from package.json.'
    package:
        required: false
        description: 'The name of the package. If provided, it overrides the package name retrieved from package.json.'
outputs:
    is-published:
        description: ''
    committed-version:
        description: ''
    retrieved-version:
        description: ''
    is-committed-version-free:
        description: ''
    result:
        description: ''
runs:
    using: 'node12'
    main: 'dist/index.js'
branding:
    icon: 'loader'
    color: 'orange'
