name: 'build-test'
on:
    pull_request:
    push:
        branches:
            - main
            - 'releases/*'

jobs:
    build:
        name: 'Build'
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - run: yarn
            - run: yarn all
    test:
        name: 'Test'
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - id: version
              uses: ./
            - name: Install dependencies
              if: steps.version.outputs.is-unpublished-version == 'true'
              run: |
                  echo "Latest published verison: ${{ steps.version.outputs.latest-published-version }}"
                  echo "Repo version: ${{ steps.version.outputs.repo-version }}"
